### ISSUE TITLE
none of the examples in README are valid

### ISSUE THREAD

**Issue by carandraug** [JamieHeather/stitchr#2]
The two examples provided in the README:

```
python stitchr.py -v TRBV7-3*01 -j TRBJ1-3*01 -cdr3 CASSPGRGTTNEKLFF
python stitchr.py -v TRAV1-2 -j TRAJ33 -cdr3 CAVERGEGF
```

do not work (see also issue #1). Manually checking the data files, it does seem that the problem is on the example, not the actual stitchr code.

**Comment by JamieHeather** [comment]
Excellent point, this was a silly mistake - those CDR3s don't use those Js! Nice easy fix
