### ISSUE TITLE
Thimble GUI example files throw error

### ISSUE THREAD

**Issue by EdGreen21** [JamieHeather/stitchr#21]
Was testing the code and thought to use the GUI mode first out of idle curiosity. Uploading the example file:
stitchr-main\Templates\GUI-Examples\human_TRA-TRB.tsv and attempting to process it (without P2A linker) leads to the following error:

gui-stitcher.py:436: UserWarning: WArning: user-provided gene TCRgenename*01 contains non-DNA sequences.... 
KeyError: ('TRA/TRB', 'HUMAN')

This is a fatal error and leads to dropping back to console. Seems like it's probably a teething error with the move to 0.91, thought I'd raise an issue (I'll go back to command line use)

**Comment by JamieHeather** [comment]
Thanks for flagging this up Ed! You're right, just a silly missed variable name when the GUI tried to upload an existing data file.

Should be fixed in the GUI version 0.4.1 / 06f168a .
