### ISSUE TITLE
stitch errors if -a option is not specified

### ISSUE THREAD

**Issue by carandraug** [JamieHeather/stitchr#3]
If the `-aa` option is not specified, then stitchr errors:

```
python stitchr.py -v TRAV13-1 -j TRAJ34 -cdr3 CAAYNTDKLIF
[...]
Traceback (most recent call last):
  File "stitchr.py", line 124, in <module>
    if input_args['aa']:
KeyError: 'aa'
```

The issue is that the code checks the value of `aa` in the options dictionary instead of its presence.

**Comment by carandraug** [comment]
I have a proposed fix on my fork.

**Comment by JamieHeather** [comment]
Another good catch, another easy fix - thanks a lot!
