### ISSUE TITLE
thimble function gives an error for LEADER sequence when stitching TCR

### ISSUE THREAD

**Issue by rita-the-scientist** [JamieHeather/stitchr#30]
Dear Jamie,
Thank you for developing this package!

I'm trying to use thimble.py function to get full paired-chain TCR sequences.
Unfortunately, for every TCR in the .tsv file (~4,500 TCRs), I get the same error:
_(TRA) Error: a LEADER sequence region has not been found for genes in the IMGT data for this chain/species. Please check your TCR and species data. Cannot stitch a sequence for TRA. (TRB) Error: a LEADER sequence region has not been found for gene in the IMGT data for this chain/species. Please check your TCR and species data. Cannot stitch a sequence for TRB. (Link) Error: need both a TRA and TRB to link.__ 

However, when I tried to stitch the same TCRs manually using stitchr.py function, it worked perfectly fine.
For example, a line in the .tsv table: 
TCR0	TRAV3	TRAJ37	CAAPPSNTGKLIF	TRBV19	TRBJ2-3	CASSTRAADTQYF - gives an error when using thimble.py
But both of these work well:
python3 stitchr.py -v TRAV3 -j TRBJ37 -cdr3 CAAPPSNTGKLIF
python3 stitchr.py -v TRBV19 -j TRBJ2-3 -cdr3 CASSTRAADTQYF

My TCR genes name should be consistent with the IMGT nomenclature.
What could be the reason for such an error and how I can fix it?
Thank you for your time.

**Comment by rita-the-scientist** [comment]
Thank you for your quick reply!
The problem was indeed in my .tsv file. 
I was assigning empty columns to my TCR dataframe through 
_df = df.assign(TRAC="", TRBC="", ...)_ and then saving it as a .tsv file by _df.to_csv('filename.tsv', sep = '\t')._  So my .tsv file had a lot of tab spaces after the TRB_CDR3 column and they were somehow causing the issue. When I saved only first seven columns in .tsv file and then manually added the rest of the header (so, not tab spaces in TCR rows), the thimble.py worked.

**Comment by JamieHeather** [comment]
Great! And yes that makes sense that it would break it - thimble makes certain assumptions about the input columns.

Thanks for flagging this up!
