### ISSUE TITLE
CDR1/2

### ISSUE THREAD

**Issue by dstcr** [JamieHeather/stitchr#32]
Works brilliantly! Thank you so much, great work.

Just had an enquiry about inclusion of CDR1/CDR2. Is there an easy way to include these, and more broadly do you see any merit in doing so? How faithful should the current approach be? 

I'm using these amino acids to then perform structural modelling for context.

Many thanks!

**Comment by JamieHeather** [comment]
Thanks, I'm very happy to hear it's working for you!

When you say include CDR1/CDR2, do you mean that you'd like new fields to allow changing these like we change CDR3?

If so I don't think that's something that's going to be a common request, and also not something that is necessarily going to be straightforward to add, which makes it unlikely I can find the time to do it myself. I think these regions are not necessarily going to be well annotated for every species/locus stitchr could work with, and making stitchr able to figure out where the CDR/FR region boundaries should be for any given allele would be a lot of work for little reward.

However if this is what you want to do there are certainly ways to do it with existing stitchr functions (and a little bit more prep work). For example, I would do something like this:

1) Pre-generate FASTA sequences for each V gene you're interested in, with multiple sequences with every combination of CDR1/CDR2 (or any other modifications) edited in already 

2) Place these in a suitable location in the stitchr data directory (found by running`stitchr -dd`), following [the guidance of the data section of the docs](https://jamieheather.github.io/stitchr/inputdata.html#providing-additional-gene-sequences)
   * Either put them either in the 'additional-genes.fasta' file and use the `-xg` flag...
   * ... or put them in the relevant FASTA file for the species you care about (taking care not to edit the gene/allele names to avoid ID clashes)

3) Then use stitchr and/or thimble to generate the specific desired rearrangements, calling each of the genes in turn
    * If you name them as different alleles of the same gene you could also make use of [the wildcard feature of thimble to automatically stitch all](https://jamieheather.github.io/stitchr/thimble.html#stitch-multiple-tcrs-per-line-with-list-and-wildcard-fields).

Does that help?

**Comment by JamieHeather** [comment]
I'm closing this for now for the reasons described above (not easy to implement and I don't think it'll be desired enough to justify the time to try). Feel free to let me know if I've misunderstood the question or if my suggested alternative strategy doesn't make sense.
