### ISSUE TITLE
Specify databases location

### ISSUE THREAD

**Issue by dcarbajo** [JamieHeather/stitchr#37]
Hi! is there a way to explicitly specify the location of the databases (TRA.fasta and TRB.fasta) to use?

I made a package to use Stitchr (and other things) and want to put the fasta files in a folder that goes with the package. However, when running it, it complains with `TRA.fasta not detected in the Data directory. Please check data exists for this species/locus combination.` cause I don't have the files in the Data/HUMAN directory anymore...

Is there a way to pass the databases location to Stitchr?

I use the importing approach as discussed in issue #35 

Thanks!

**Comment by JamieHeather** [comment]
Hello hello,

As it currently stands Stitchr expects the input reference sequences to be in the expected directory produced during its installation via `pip`, as that was the most straightforward way I could think to ensure cross-platform support. Also this design intentionally requires the downloading of reference sequences from primary sources, to both ensure use of current versions and to abide by different database licenses. I hadn't anticipated your use case, which I appreciate is not well catered to under the current design.

However it should be fairly simple to achieve what you want with the package as it stands without maintaining your own custom fork of Stitchr. You would just need to move whatever reference data you're including with your package to the Stitchr directory (which you can find by running `stitchr -dd`) when you initialise your package. Also remember that it doesn't have to be in Data/HUMAN directory, you could call it whatever you like (e.g. Data/myreferencedata), you would just need to tell Stitchr which directory to use at runtime via the `--species` flag (`stitchr -s myreferencedata ...`). Alternatively, while I haven't tried it, you might also be able to use some symlink trickery or similar to locate the data where you want it while maintaining Stitchr's required paths.

Failing that you could always dispense with the `pip` installable version and instead use the v.1.0.0 release, in which the reference directories are located relative to the scripts directory. The differences between the current v1.1.2 and v.1.1.0 are mostly those made to make it installable - so while you'd have to change how you pass data to/from stitchr it should produce the same results (although you would miss out potential future updates and bug fixes etc).

Hope that helps,
Jamie

**Comment by dcarbajo** [comment]
Thanks for the prompt response! I think after all it should not be a problem... what I am trying to do now is include the installation of stitchr and the databases in a Dockerfile to run it as a container. That way I can have everything in place, so the above should not be a problem...

If you happen to have an example at hand on how I can install stitchr via a Dockerfile, I would also appreciate (I'm just starting with Docker); I think something along the lines of `RUN pip install stitchr` should do (though I need to install it in a specific conda environment, so I will have to figure out.

Thanks!

**Comment by JamieHeather** [comment]
I am afraid I have essentially no expertise in creating dockerfiles, so I can't help with examples.

However I think you would need to also run `pip install IMGTgeneDL` in whatever environment you use, and then (assuming you just want a vanilla germline reference) the appropriate `stitchrdl` command to grab the data for whatever species you're interested in (e.g. `stitchrdl -s human`). That should then deposit the necessary data in the appropriate directory.

Do please share your dockerfile example if you get it working in case others have a similar use case!
Cheers

**Comment by dcarbajo** [comment]
I managed to make it work! It was a bit convoluted since I wanted to install `stitchr` in a conda environment inside a Docker image.

I'm not very proficient with Docker, but since I had all the commands already in R, I decided to not reinvent the wheel and call them pretty much as is inside the Dockerfile. These are the relevant lines:

```
RUN Rscript -e "reticulate::install_miniconda()"
RUN Rscript -e "reticulate::conda_create(envname = 'my_environment', packages = 'python=3.10')"

RUN Rscript -e "reticulate::py_install(c('stitchr','crowelab_pyir'), method = 'conda', envname = 'my_environment', pip = TRUE)"

RUN /root/.local/share/r-miniconda/bin/conda run -n r-reticulate stitchrdl -s human
```

**Comment by JamieHeather** [comment]
Thanks for sharing it!
