### ISSUE TITLE
Can't get demo TCRs or help functions to print

### ISSUE THREAD

**Issue by wyattmcdonnell** [JamieHeather/stitchr#4]
Hey Jamie—have tried a few times with Python 3.6.5 and can't seem to get either of the example calls to work, or even the help command. I have biopython installed and have no issue importing it as `import Bio`. All three of the following snippets: 

1. Demo TCR 1
```
python stitchr.py -v TRBV7-3*01 -j TRBJ1-1*01 -cdr3 CASSYLQAQYTEAFF
```
2. Demo TCR 2
```
python stitchr.py -v TRAV1-2 -j TRAJ33 -cdr3 CAVLDSNYQLIW
```
3. Help menu
```
python stitchr.py -h
```
... all produce the exact same error message:
```
File "stitchr.py", line 81
    print "\tCannot find", r.upper(), "gene", input_args[r] + \
                        ^
SyntaxError: invalid syntax
```
I tried poking around and adding some quotes around lines 78-83 but can't seem to find exactly where the missing apostrophe is. 

Best wishes,
Wyatt

**Comment by JamieHeather** [comment]
Hi Wyatt,

This is actually written for Python 2.7, so it would probably take quite a few tweaks to get it working in Python 3.

This is a very good point though, as it doesn't actually say this anywhere in the repo - I'll be sure to add this to the README! Thanks for the heads up.

Best,
Jamie

**Comment by wyattmcdonnell** [comment]
Haha, that would explain things... a brand new conda env with 2.7 works perfectly. Thanks Jamie!
