### ISSUE TITLE
fails weirdly if it can't find tcr data

### ISSUE THREAD

**Issue by carandraug** [JamieHeather/stitchr#6]
```
$ python stitchr.py -v TRAV29DV5 -j TRAJ23 -cdr3 CAAFNQGGKLIF
Warning: gene TRAV29DV5*01
Traceback (most recent call last):
  File "stitchr.py", line 90, in <module>
    functionality[gene][allele] + "\', and thus may not express or function correctly."
TypeError: cannot concatenate 'str' and 'list' objects
```

The problem is that `functionality[gene][allele]` is an empty list. I'm guessing the code should have never reach that state.

**Comment by carandraug** [comment]
For what is worth, I know the issue is that "TRAV29DV5" is incorrect. The bug is about how the program fails.

**Comment by JamieHeather** [comment]
This had actually incidentally already been solved on the testing branch where I introduced rudimentary coverage of mouse TCRs. I can't recreate this behaviour with the current version (0.2.2) - which has now been merged with the master branch - so I think this should be sorted now.

Thanks again for catching these.
