### ISSUE TITLE
exits with an error but zero status code

### ISSUE THREAD

**Issue by carandraug** [JamieHeather/stitchr#7]
Multiple functions in `functions.py` exit with `sys.exit` if they fail input validation. However, they exit wiith a zero status code:

```
$ python stitchr.py -v TRBV17 -j TRBJ1-2 -cdr3 YSSGEAGSGYTF
Error, CDR3 does not fit expected parameters. Please ensure it includes the conserved C/F residues.
$ echo $?
0
```

The implications of exiting with a zero status code, is that for all purposes the script reports exiting with success. The status code should be non-zero.

I would recommend raising `ValueError` instead of calling `sys.exit`, at least for this specific case.

**Comment by JamieHeather** [comment]
This is an excellent point, and not something I had considered. I've swapped in these/other appropriate (I hope!) exceptions.

Thanks!
